"""Initial migration

Revision ID: 0001_initial
Revises: 
Create Date: 2026-04-03 00:00:00.000000
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by hand ###
    op.create_table(
        "job_offers",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("fingerprint", sa.String(length=32), nullable=True, unique=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("institution", sa.String(length=512), nullable=False),
        sa.Column("salary_bruto", sa.Numeric(14, 2), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("region", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=255), nullable=True),
        sa.Column("url", sa.String(length=1024), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )

    op.create_table(
        "job_offer_sources",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("job_offer_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("job_offers.id"), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("raw_data", postgresql.JSONB, nullable=False),
        sa.Column("original_state", sa.String(length=32), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.UniqueConstraint("source", "external_id", name="uq_job_offer_sources_source_external_id"),
    )

    op.create_index("ix_job_offer_sources_job_offer_id", "job_offer_sources", ["job_offer_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by hand ###
    op.drop_index("ix_job_offer_sources_job_offer_id", table_name="job_offer_sources")
    op.drop_table("job_offer_sources")
    op.drop_table("job_offers")
    # ### end Alembic commands ###
